// <auto-generated />
using System;
using ContaService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContaService.API.Migrations
{
    [DbContext(typeof(ContaServiceContext))]
    [Migration("20200802233148_InitialCatalog")]
    partial class InitialCatalog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ContaService.Domain.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int>("TipoOperacao");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("ContaService.Domain.Models.Lancamento", b =>
                {
                    b.OwnsOne("ContaService.Domain.Models.ContaCorrente", "Conta", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<string>("Numero")
                                .IsRequired();

                            b1.Property<decimal>("Saldo");

                            b1.ToTable("ContaCorrente");

                            b1.HasOne("ContaService.Domain.Models.Lancamento")
                                .WithOne("Conta")
                                .HasForeignKey("ContaService.Domain.Models.ContaCorrente", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
