// <auto-generated />
using System;
using ContaService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContaService.API.Migrations
{
    [DbContext(typeof(ContaServiceContext))]
    partial class ContaServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ContaService.Domain.Models.ContaCorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Numero")
                        .IsRequired();

                    b.Property<decimal>("Saldo");

                    b.HasKey("Id");

                    b.ToTable("ContaCorrente");

                    b.HasData(
                        new { Id = 1, Numero = "12345-6", Saldo = 1000m },
                        new { Id = 2, Numero = "54321-0", Saldo = 1000m },
                        new { Id = 3, Numero = "02468-9", Saldo = 1000m }
                    );
                });

            modelBuilder.Entity("ContaService.Domain.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContaId");

                    b.Property<DateTime>("Data");

                    b.Property<decimal>("SaldoAtual");

                    b.Property<int>("TipoOperacao");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Lancamento");

                    b.HasData(
                        new { Id = 1, ContaId = 1, Data = new DateTime(2020, 8, 5, 19, 2, 54, 569, DateTimeKind.Utc), SaldoAtual = 1000m, TipoOperacao = 1, Valor = 1000m },
                        new { Id = 2, ContaId = 2, Data = new DateTime(2020, 8, 5, 19, 2, 54, 569, DateTimeKind.Utc), SaldoAtual = 1000m, TipoOperacao = 1, Valor = 1000m },
                        new { Id = 3, ContaId = 3, Data = new DateTime(2020, 8, 5, 19, 2, 54, 569, DateTimeKind.Utc), SaldoAtual = 1000m, TipoOperacao = 1, Valor = 1000m }
                    );
                });

            modelBuilder.Entity("ContaService.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessKey");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new { Id = 1, AccessKey = "6a15395e10db3e76b4a953ffb439d32da" },
                        new { Id = 2, AccessKey = "a4ae2f7f58dc1e0973fb79c9677a09161" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
